name: Test Go Code Examples in Docker

on:
  pull_request:
    paths:
      - "go/example/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '8.0'
      - name: Install MongoDB Database Tools to load sample data
        run: |
          curl https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.10.0.deb --output mdb-db-tools.deb
          sudo apt install ./mdb-db-tools.deb
      - name: Download sample data
        run: curl  https://atlas-education.s3.amazonaws.com/sampledata.archive -o sampledata.archive
      - name: Add sample data to database
        run: mongorestore --archive=sampledata.archive --port=27017
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: |
          cd go/
          go mod download
      - name: Create environment file with connection string
        run: |
          echo $PWD
          cd go/
          echo $PWD
          touch .env
          echo "ATLAS_CONNECTION_STRING=\"mongodb://localhost:<port-number>/?directConnection=true\"" >> .env
      - name: Run tests
        run: |
          echo $PWD
          cd go/tests/
          echo $PWD
          go test -v -p 1 ./...
